name: Deploy to GitHub Pages & Build Production Release

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Customize BasePath for GitHub Pages
        run: |
          sed -i "s/basePath: '\/spb'/basePath: '\/simple-productivity-blocker'/g" website/next.config.mjs

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: './website/package-lock.json'

      - name: Install Dependencies
        run: npm ci
        working-directory: ./website

      - name: Build Next.js Site
        run: npm run build
        working-directory: ./website

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./website/out

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements-lock.txt

      - name: Install NSIS
        run: choco install nsis

      - name: Execute Build Script
        run: .\build.ps1

      - name: Upload Installer Artifact
        uses: actions/upload-artifact@v4
        with:
          name: spb-production-installer
          path: dist/spb_setup.exe
